version: "3"
services:
  nginx:
    ports:
      - "80:80"
    depends_on:
      - app
  app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment: 
      - NODE_ENV=production
    command: npm start